[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期処理用のプラグイン
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]] #footer
repo = 'itchyny/lightline.vim'

#
#  補完 {
#
[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
hook_add = '''
      if has('pythonx')
            let s:py = 'pythonx'
            let s:pyeval = function('pyxeval')
      elseif has('python3')
            let s:py = 'python3'
            let s:pyeval = function('py3eval')
      else
            let s:py = 'python'
            let s:pyeval = function('pyeval')
      endif
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['ujihisa/neco-look', 'Shougo/neco-syntax']
hook_add = '''
      let g:deoplete#enable_at_startup = 1
'''
#
#  } 補完
#

[[plugins]] # 構文エラーチェック
repo = 'scrooloose/syntastic'
hook_add = '''
      let g:syntastic_enable_signs = 1
      let g:syntastic_always_populate_loc_list = 1
      let g:syntastic_check_on_open = 1
'''

[[plugins]] # スクリプト実行 Ctrl-r
repo = 'thinca/vim-quickrun'
hook_add = """
      nnoremap <silent> <C-r> :QuickRun<CR>
      let g:quickrun_config = {
            \'_': {
            \      'split': 'vertical',
            \},
            \'rust': {
            \      'exec' : 'cargo check'
            \},
            \'nim': {
                  \ 'command': 'nim',
                  \ 'cmdopt': 'c -r -d:ssl --verbosity:0',
                  \ 'hook/sweep/files': '%S:p:r',
                  \ 'tempfile': '%{substitute(tempname(), ''\(\d\+\)$'', ''nim\1.nim'', '''')',
            \},
            \'swift': {
                  \ 'command': 'xcrun',
                  \ 'cmdopt': 'swift',
                  \ 'exec': 'swift build',
            \},
            \'elm': {
                  \ 'exec': "elm-make %s --output elm.js",
            \},
      \}

      set splitright
"""

[[plugins]] # htmlのマッチしている先を教えてくれる
repo = 'valloric/matchtagalways'
on_ft = 'html'
on_ft = 'php'
hook_souce = '''
      let g:mta_use_matchparen_group = 1
      let g:mta_filetypes = { 'html' : 1, 'php' : ,1 }
'''

[[plugins]] # 複数行のコメントアウト ctrl+k
repo = 'tyru/caw.vim.git'
hook_add = '''
      nmap <C-K> <Plug>(caw:i:toggle)
      vmap <C-K> <Plug>(caw:i:toggle)
'''

[[plugins]] # カーソル下のハイライトをトグルする space+mで検索
repo = 't9md/vim-quickhl'
hook_add = '''
      map <Space>m <Plug>(quickhl-manual-this)
      map <Space>M <Plug>(quickhl-manual-reset)
'''


[[plugins]] # indent
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
      let g:indent_guides_start_level=2
      let g:indent_guides_enable_on_vim_startup = 1
      let g:indent_guides_guide_size = 1
      let g:indent_guides_auto_colors = 0
      autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=235
      autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=235
'''

[[plugins]] # テキスト整形 visualモードで ga
repo = 'junegunn/vim-easy-align'
hook_add = '''
      xmap ga <Plug>(EasyAlign)
      nmap ga <Plug>(EasyAlign)
'''

[[plugins]] #ファイル構造
repo = 'scrooloose/nerdtree'
hook_add = '''
      let NERDTreeShowHidden=1
      let g:NERDTreeDirArrows = 1
      map <silent> <C-n> :NERDTreeToggle<CR>
'''

[[plugins]] #color確認
repo = 'gko/vim-coloresque'

[[plugins]] #画面サイズを編集 ctrl+e
repo = 'simeji/winresizer'

[[plugins]] # j, k移動高速化
repo = 'rhysd/accelerated-jk'

# Markdown {
[[plugins]] # quote内のプログラムをシンタックスハイライトする
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

[[plugins]] # 編集中のMarkdownファイルのプレビューを作成する
repo = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]] # プレビューをブラウザで開いてくれる
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
hook_add = '''
      map <silent> :MD<CR> :PrevimOpen<CR>
'''
# }

#[ lisp
[[plugins]]
repo = "l04m33/vlime"
rtp = "vim/"
on_ft = "lisp"

[[plugins]]
repo = 'vim-scripts/paredit.vim'
on_ft = ['lisp', 'clojure']
#]


# rust {
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#racer_binary='/usr/local/bin/racer'
    let g:deoplete#sources#rust#rust_source_path='/usr/local/Cellar/rust/1.25.0/lib/rustlib/manifest-rustc}'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
    nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
    nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''
# }

# go {
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]] # syntax
repo = 'zchee/deoplete-go'
on_ft = ['go']
# }

[[plugins]] # elixir
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir']

# haskell {
[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']
# }

[[plugins]] # nim
repo = 'zah/nim.vim'
on_ft = ['nim']

# swift {
[[plugins]] # ハイライト
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]] # syntax
repo = 'kballard/vim-swift'
on_ft = ['swift']

[[plugins]] # 保管
repo = 'landaire/deoplete-swift'
on_ft = ['swift']
# }

# clojure {
[[plugins]]
repo = 'tpope/vim-fireplace'
on_ft = ['clojure']
# }

# elm {
# npm install -g elm
# npm install -g elm-test
# npm install -g elm-oracle
# npm install -g elm-format
[[plugins]]
repo = 'elmcast/elm-vim'
on_ft = ["elm"]
# }

# Ocaml {
# }

# HTML {
[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html", "tpl"]
add_hook = '''
let g:user_emmet_leader_key='<c-y>'
'''

# }

# ruby {
[[plugins]] # end補完
repo = 'tpope/vim-endwise'
on_ft = ["ruby"]

[[plugins]] # local
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = ["ruby"]

[[plugins]] # synatax
repo = 'marcus/rsense'
on_ft = ["ruby"]
# }

[[plugins]] # toml
repo = 'cespare/vim-toml'
on_ft = ['toml']

#カラースキーマ {
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'christophermca/meta5'

[[plugins]]
repo = 'dracula/vim'
#}
